version: "3.5"
services:
  php:
    working_dir: /var/www/dev-php
    build: ./docker
    volumes:
      - .:/var/www/dev-php:cached
    environment:
      APP_DEBUG: "true"
    ports:
      - 127.0.0.1:80:80
    links:
      - mysql
      - mailhog
    depends_on:
      - mysql

  mysql:
    image: percona:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - 127.0.0.1:3306:3306

  mailhog:
    image: mailhog/mailhog
    ports:
      - 127.0.0.1:8025:8025
